import { Layer2, Provenance, Security } from "./index.js";
const tests=[];function test(name,fn){try{fn();tests.push({name,passed:true});}catch(error){tests.push({name,passed:false,error:error.message});}}function assert(c,m){if(!c)throw new Error(m);}
test("circle relationships",()=>{assert(Layer2.Relationships.classifyCircleRelationship({x:0,y:0,radius:5},{x:10,y:0,radius:5}).relationship==="EXTERNALLY_TANGENT","tangent classification failed");});
test("3D transforms",()=>{const p=Layer2.Transforms.rotateZ({x:1,y:0,z:2},Math.PI/2);assert(Math.abs(p.x)<1e-9&&Math.abs(p.y-1)<1e-9&&p.z===2,"rotation failed");});
test("spherical round trip",()=>{const p=Layer2.Spatial.sphericalToCartesian({lat:45,lon:-93,radius:10});const q=Layer2.Spatial.cartesianToSpherical(p);assert(Math.abs(q.lat-45)<1e-9&&Math.abs(q.lon+93)<1e-9,"spherical conversion failed");});
test("great-circle distance",()=>{const d=Layer2.Spatial.greatCircleDistance({lat:0,lon:0},{lat:0,lon:90},1);assert(Math.abs(d-Math.PI/2)<1e-9,"great-circle failed");});
test("reconstruction verification",()=>{const out=Layer2.Reconstruction.verifyReconstruction({observed:[1,2,3],predicted:[1,2,3],tolerance:0,context:{authorized:true,principal:"self-test"}});assert(out.result.verified,"reconstruction failed");assert(Provenance.verifyAuditEvent(out.audit),"audit verification failed");});
test("tamper-evident provenance",()=>{const event=Provenance.createAuditEvent({operation:"TEST",module:"L2",inputs:{a:1},result:{b:2}});assert(Provenance.verifyAuditEvent(event),"valid event failed");assert(!Provenance.verifyAuditEvent({...event,status:"ALTERED"}),"tamper not detected");});
test("security validation",()=>{assert(Security.assertPlainData({safe:[1,2,3]}),"plain data rejected");let blocked=false;try{Security.requireAuthorizedContext({authorized:false,principal:"x"});}catch{blocked=true;}assert(blocked,"unauthorized context accepted");});
console.log("\nGIE LAYER 2 SELF TEST\n=====================");for(const r of tests)console.log(r.passed?`PASS  ${r.name}`:`FAIL  ${r.name}: ${r.error}`);const failed=tests.filter(r=>!r.passed);if(failed.length)process.exit(1);console.log("\nALL GIE LAYER 2 TESTS PASSED");
