import { assertPlainData } from "../security/validation.js";

function idOf(v){return String(v);}
export function createWorldGraph({nodes=[],edges=[]}={}){
  assertPlainData({nodes,edges});
  const nodeMap=new Map();
  for(const n of nodes){if(!n||n.id===undefined)throw new Error("Every node requires an id.");const id=idOf(n.id);if(nodeMap.has(id))throw new Error(`Duplicate node id: ${id}`);nodeMap.set(id,Object.freeze({...n,id}));}
  const normalizedEdges=edges.map((e,i)=>{if(!e||e.from===undefined||e.to===undefined)throw new Error(`Edge ${i} requires from and to.`);const from=idOf(e.from),to=idOf(e.to);if(!nodeMap.has(from)||!nodeMap.has(to))throw new Error(`Edge ${i} references an unknown node.`);const weight=e.weight??1;if(!Number.isFinite(weight)||weight<0)throw new Error(`Edge ${i} has invalid weight.`);return Object.freeze({...e,id:e.id??`e${i}`,from,to,weight,directed:e.directed!==false});});
  return Object.freeze({nodes:Object.freeze([...nodeMap.values()]),edges:Object.freeze(normalizedEdges)});
}
export function adjacency(graph,{reverse=false}={}){const m=new Map(graph.nodes.map(n=>[n.id,[]]));for(const e of graph.edges){const a=reverse?e.to:e.from,b=reverse?e.from:e.to;m.get(a).push({node:b,edge:e});if(!e.directed)m.get(b).push({node:a,edge:e});}return m;}
export function shortestPath(graph,start,end){start=idOf(start);end=idOf(end);const adj=adjacency(graph),dist=new Map(graph.nodes.map(n=>[n.id,Infinity])),prev=new Map();if(!dist.has(start)||!dist.has(end))throw new Error("Path endpoints must exist.");dist.set(start,0);const open=new Set(dist.keys());while(open.size){let u=null,best=Infinity;for(const x of open){if(dist.get(x)<best){best=dist.get(x);u=x;}}if(u===null||best===Infinity)break;open.delete(u);if(u===end)break;for(const {node,edge} of adj.get(u)){const alt=best+edge.weight;if(alt<dist.get(node)){dist.set(node,alt);prev.set(node,u);}}}if(dist.get(end)===Infinity)return null;const path=[];for(let x=end;x!==undefined;x=prev.get(x)){path.unshift(x);if(x===start)break;}return {path,distance:dist.get(end)};}
export function dependencyClosure(graph,nodeId,{direction="downstream"}={}){nodeId=idOf(nodeId);const adj=adjacency(graph,{reverse:direction==="upstream"});if(!adj.has(nodeId))throw new Error(`Unknown node: ${nodeId}`);const seen=new Set(),stack=[nodeId];while(stack.length){const u=stack.pop();for(const {node} of adj.get(u)){if(!seen.has(node)){seen.add(node);stack.push(node);}}}seen.delete(nodeId);return [...seen];}
export function detectCycles(graph){const adj=adjacency(graph),state=new Map(),stack=[],cycles=[];function visit(u){state.set(u,1);stack.push(u);for(const {node:v} of adj.get(u)){if(state.get(v)===1){const i=stack.indexOf(v);cycles.push([...stack.slice(i),v]);}else if(!state.get(v))visit(v);}stack.pop();state.set(u,2);}for(const n of graph.nodes)if(!state.get(n.id))visit(n.id);return cycles;}
export function topologicalOrder(graph){if(graph.edges.some(e=>!e.directed))throw new Error("Topological order requires directed edges.");const indeg=new Map(graph.nodes.map(n=>[n.id,0]));for(const e of graph.edges)indeg.set(e.to,indeg.get(e.to)+1);const q=[...indeg].filter(([,d])=>d===0).map(([id])=>id),out=[];while(q.length){const u=q.shift();out.push(u);for(const {node:v} of adjacency(graph).get(u)){indeg.set(v,indeg.get(v)-1);if(indeg.get(v)===0)q.push(v);}}if(out.length!==graph.nodes.length)throw new Error("Graph contains a dependency cycle.");return out;}
