import assert from "node:assert/strict";
import { qualifyEvidence } from "./layer4/evidence.js";
import { createAnalysisJob, executeAnalysisJob, verifyApplicationResult, createDualAudienceReport, createExportManifest } from "./layer6/application.js";
import { GIE_ENGINE } from "./core/engineRegistry.js";
const pass=n=>console.log(`PASS  ${n}`);
const ctx={authorized:true,principal:"test-operator",tenantId:"customer-a"};
const ev=(v,m)=>qualifyEvidence({source:`sensor-${m}`,value:v,method:m,independent:true,reproducible:true,integrity:true});
console.log("\nGIE LAYER 6 SELF TEST\n=====================");
const candidate={id:"fix-a",description:"Correct verified dependency bottleneck",recommendation:"Apply verified correction",confidence:.95,impact:.9,feasibility:.9,risk:.1,evidence:[ev(42,"method-a"),ev(42,"method-b")]};
const job=createAnalysisJob({context:ctx,tenantId:"customer-a",objective:"Restore platform operating standard",observations:[{metric:"latency",value:42}],candidates:[candidate]});
assert.equal(job.status,"CREATED"); pass("authorized customer job creation");
assert.throws(()=>createAnalysisJob({context:ctx,tenantId:"customer-b",objective:"x"}),/isolation/); pass("customer isolation boundary");
const result=executeAnalysisJob({context:ctx,job}); assert.equal(result.status,"VERIFIED_COMPLETE"); pass("end-to-end verified execution");
assert.equal(verifyApplicationResult(result),true); pass("application result integrity");
const report=createDualAudienceReport({context:ctx,result}); assert.equal(report.business.status,"VERIFIED_RECOMMENDATION_AVAILABLE"); assert.equal(report.technical.selectedId,"fix-a"); pass("business and technical reporting");
const noJob=createAnalysisJob({context:ctx,tenantId:"customer-a",objective:"Unknown issue",candidates:[]}); const noResult=executeAnalysisJob({context:ctx,job:noJob}); const noReport=createDualAudienceReport({context:ctx,result:noResult}); assert.equal(noReport.business.recommendation,null); pass("no unverified recommendation exposed");
const manifest=createExportManifest({context:ctx,report}); assert.equal(manifest.reportHash,report.reportHash); pass("tamper-evident export manifest");
const tampered={...result,status:"VERIFIED_COMPLETE_CHANGED"}; assert.equal(verifyApplicationResult(tampered),false); pass("application tamper detection");
assert.throws(()=>executeAnalysisJob({context:{authorized:false,principal:"x",tenantId:"customer-a"},job}),/Authorized/); pass("unauthorized execution blocked");
assert.equal(GIE_ENGINE.layers.layer6,"APPLICATION_CUSTOMER_INTERFACE"); assert.equal(GIE_ENGINE.version,"1.0.0"); pass("six-layer engine registry complete");
assert.ok(Date.parse(job.createdAt)); assert.ok(Date.parse(result.completedAt)); assert.ok(Date.parse(report.generatedAt)); assert.ok(Date.parse(manifest.exportedAt)); pass("timestamped lifecycle provenance");
console.log("\nALL GIE LAYER 6 TESTS PASSED");
